// SharpIQ — ARCHIVO DE DATOS
// Actualizado: 2026-05-29
// NO editar manualmente

const PROXIMOS_EVENTOS = [
  {
    fecha:      "25/06/26",
    partido:    "Turkey vs USA",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Visitante",
    cuota:      "1.44",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "25/06/26",
    partido:    "Paraguay vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.6",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "63",
    resultado:  "push"
  },
  {
    fecha:      "25/06/26",
    partido:    "Tunisia vs Netherlands",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 4.5 Goles",
    cuota:      "1.39",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "pendiente"
  },
  {
    fecha:      "25/06/26",
    partido:    "Japan vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.32",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "75",
    resultado:  "pendiente"
  },
  {
    fecha:      "25/06/26",
    partido:    "Turkey vs USA",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.62",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "61",
    resultado:  "loss"
  },
  {
    fecha:      "25/06/26",
    partido:    "Japan vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "pendiente"
  },
  {
    fecha:      "25/06/26",
    partido:    "Curaçao vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.76",
    hora:       "15:05 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "25/06/26",
    partido:    "Curaçao vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.53",
    hora:       "15:05 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "64",
    resultado:  "loss"
  },
  {
    fecha:      "25/06/26",
    partido:    "Tunisia vs Netherlands",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +3.5",
    cuota:      "1.38",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "pendiente"
  },
  {
    fecha:      "25/06/26",
    partido:    "Ecuador vs Germany",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.53",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "64",
    resultado:  "win"
  },
  {
    fecha:      "25/06/26",
    partido:    "Ecuador vs Germany",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Visitante",
    cuota:      "1.3",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "76",
    resultado:  "loss"
  },
  {
    fecha:      "25/06/26",
    partido:    "Paraguay vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.73",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "58",
    resultado:  "loss"
  },
  {
    fecha:      "24/06/26",
    partido:    "South Africa vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.77",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Czech Republic vs Mexico",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.35",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "73",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "South Africa vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.38",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "24/06/26",
    partido:    "Morocco vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.33",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "76",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Scotland vs Brazil",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2.25",
    cuota:      "1.4",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "24/06/26",
    partido:    "Morocco vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +3",
    cuota:      "1.33",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Scotland vs Brazil",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Visitante",
    cuota:      "1.33",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Switzerland vs Canada",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.91",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "55",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Bosnia & Herzegovina vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "2.08",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "49",
    resultado:  "loss"
  },
  {
    fecha:      "24/06/26",
    partido:    "Bosnia & Herzegovina vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.42",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Switzerland vs Canada",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.41",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Czech Republic vs Mexico",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.34",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "73",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "Colombia vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1.5",
    cuota:      "1.54",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "64",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "Colombia vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1.75",
    cuota:      "1.38",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "Panama vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.98",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "52",
    resultado:  "loss"
  },
  {
    fecha:      "23/06/26",
    partido:    "Panama vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Visitante",
    cuota:      "1.48",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "England vs Ghana",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.61",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "loss"
  },
  {
    fecha:      "23/06/26",
    partido:    "England vs Ghana",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2.5",
    cuota:      "1.6",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "Portugal vs Uzbekistan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.7",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "60",
    resultado:  "loss"
  },
  {
    fecha:      "23/06/26",
    partido:    "Portugal vs Uzbekistan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.5",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "Cincinnati Reds vs Milwaukee Brewers",
    liga:       "MLB",
    prediccion: "Gana Cincinnati Reds",
    cuota:      "2.02",
    hora:       "18:11 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.0",
    prob:       "50",
    resultado:  "loss"
  },
  {
    fecha:      "22/06/26",
    partido:    "Jordan vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    hora:       "22:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "Norway vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.41",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "22/06/26",
    partido:    "France vs Iraq",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 4.5 Goles",
    cuota:      "1.53",
    hora:       "16:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "65",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "Shamrock Rovers vs Derry City",
    liga:       "League of Ireland",
    prediccion: "Ambos No Marcan",
    cuota:      "1.75",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "22/06/26",
    partido:    "Jordan vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Visitante",
    cuota:      "1.57",
    hora:       "22:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "63",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "Norway vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1",
    cuota:      "1.35",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "73",
    resultado:  "push"
  },
  {
    fecha:      "22/06/26",
    partido:    "France vs Iraq",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.35",
    hora:       "16:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "73",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "Argentina vs Austria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "Argentina vs Austria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.33",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "New Zealand vs Egypt",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.35",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "73",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "New Zealand vs Egypt",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Visitante",
    cuota:      "1.65",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "60",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "Uruguay vs Cape Verde",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.4",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "Uruguay vs Cape Verde",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.46",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "68",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "Belgium vs Iran",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.44",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "21/06/26",
    partido:    "Belgium vs Iran",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.44",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "Spain vs Saudi Arabia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Under 10.5",
    cuota:      "1.76",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "Spain vs Saudi Arabia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.38",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Tunisia vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.37",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Tunisia vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Visitante",
    cuota:      "1.51",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Ecuador vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Germany vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2.25",
    cuota:      "1.32",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "75",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Germany vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2",
    cuota:      "1.35",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Netherlands vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "loss"
  },
  {
    fecha:      "20/06/26",
    partido:    "Netherlands vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.34",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Ecuador vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "1.44",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "68",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Turkey vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.94",
    hora:       "22:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "52",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Turkey vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.38",
    hora:       "22:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Brazil vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.36",
    hora:       "19:30 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Connecticut Sun vs Toronto Tempo",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "1.92",
    hora:       "18:40 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.1",
    prob:       "53",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Brazil vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 4.5 Goles",
    cuota:      "1.51",
    hora:       "19:30 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Scotland vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.81",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Scotland vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.47",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "USA vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.3",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "76",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "USA vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.39",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Hamilton Tiger-Cats vs BC Lions",
    liga:       "CFL",
    prediccion: "Gana Hamilton Tiger-Cats",
    cuota:      "1.87",
    hora:       "18:30 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "2.2",
    prob:       "56",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Sport Recife vs Atletico Goianiense",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.91",
    hora:       "19:02 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "76",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Mexico vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.48",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Universidad de Chile vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.79",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "79",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Mexico vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.42",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Canada vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.33",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.4",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Indiana Fever vs Atlanta Dream",
    liga:       "WNBA",
    prediccion: "Gana Indiana Fever",
    cuota:      "2.0",
    hora:       "18:40 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.4",
    prob:       "51",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Czech Republic vs South Africa",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.41",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "push"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.6",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Canada vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.49",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Czech Republic vs South Africa",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.4",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "push"
  },
  {
    fecha:      "17/06/26",
    partido:    "Uzbekistan vs Colombia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Ghana vs Panama",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +0.75",
    cuota:      "1.46",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Ghana vs Panama",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.49",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "England vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1.5",
    cuota:      "1.41",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Uzbekistan vs Colombia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2",
    cuota:      "1.4",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "70",
    resultado:  "push"
  },
  {
    fecha:      "17/06/26",
    partido:    "England vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.38",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Portugal vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.31",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "75",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Portugal vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.45",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "68",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Connecticut Sun vs Washington Mystics",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "2.25",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.0",
    prob:       "46",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Austria vs Jordan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.4",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1",
    cuota:      "2.18",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "49",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2",
    cuota:      "1.32",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "77",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Austria vs Jordan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.43",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Over 3.5",
    cuota:      "1.74",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "61",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.48",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Under 8.5",
    cuota:      "1.83",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.36",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 2.5",
    cuota:      "2.2",
    hora:       "17:05 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "49",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 3.5",
    cuota:      "1.51",
    hora:       "17:05 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.7",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.4",
    prob:       "60",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.57",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "63",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.61",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "63",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Over 2.5",
    cuota:      "1.4",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 7.5",
    cuota:      "1.42",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "2.0",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "51",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Sweden vs Tunisia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 4.5",
    cuota:      "1.47",
    hora:       "21:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Qatar vs Switzerland",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2.5",
    cuota:      "1.48",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Brazil vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local -0.25",
    cuota:      "1.48",
    hora:       "17:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "14/06/26",
    partido:    "Germany vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "1.44",
    hora:       "12:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "14/06/26",
    partido:    "Juventude vs Ponte Preta",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.65",
    hora:       "09:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "12/06/26",
    partido:    "USA vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 3.5",
    cuota:      "2.12",
    hora:       "20:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "13/06/26",
    partido:    "Louisville Kings vs DC Defenders",
    liga:       "UFL",
    prediccion: "Gana Louisville Kings",
    cuota:      "2.0",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Coquimbo Unido vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.83",
    hora:       "11:30 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "12/06/26",
    partido:    "Canada vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.43",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "10/06/26",
    partido:    "Sport Recife vs Athletic Club (MG)",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.75",
    hora:       "19:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "08/06/26",
    partido:    "Vila Nova vs Botafogo",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.49",
    hora:       "18:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "07/06/26",
    partido:    "ThSV Eisenach vs HSV Hamburg",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana ThSV Eisenach",
    cuota:      "1.67",
    hora:       "08:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "THW Kiel vs TBV Lemgo",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana THW Kiel",
    cuota:      "1.71",
    hora:       "08:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "Bergischer HC vs Frisch Auf Göppingen",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana Frisch Auf Göppingen",
    cuota:      "1.92",
    hora:       "08:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "06/06/26",
    partido:    "FC Tokyo vs Cerezo Osaka",
    liga:       "J-League",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.7",
    hora:       "00:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "05/06/26",
    partido:    "Texas Rangers vs Cleveland Guardians",
    liga:       "MLB",
    prediccion: "Gana Texas Rangers",
    cuota:      "2.24",
    hora:       "19:16 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "06/06/26",
    partido:    "Tokyo Verdy vs Gamba Osaka",
    liga:       "J-League",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.5",
    hora:       "02:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "04/06/26",
    partido:    "HSV Hamburg vs HSG Wetzlar",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana HSV Hamburg",
    cuota:      "1.77",
    hora:       "12:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "02/06/26",
    partido:    "Carolina Hurricanes vs Vegas Golden Knights",
    liga:       "NHL",
    prediccion: "Gana Vegas Golden Knights",
    cuota:      "3.0",
    hora:       "19:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "31/05/26",
    partido:    "Palmeiras vs Chapecoense",
    liga:       "Brasileirao Serie A",
    prediccion: "Gana Palmeiras",
    cuota:      "1.37",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "31/05/26",
    partido:    "Gent vs Genk",
    liga:       "Belgian First Div",
    prediccion: "Under 2.5 Goles",
    cuota:      "2.05",
    hora:       "11:30 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "29/05/26",
    partido:    "Nice vs Saint Etienne",
    liga:       "Ligue 1",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.62",
    hora:       "13:45 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Carolina Hurricanes vs Montréal Canadiens",
    liga:       "NHL",
    prediccion: "Gana Carolina Hurricanes",
    cuota:      "1.70",
    hora:       "19:15 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Boca Juniors vs U. Católica (Chile)",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "2.01",
    hora:       "19:30 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "30/05/26",
    partido:    "Athletic Club (MG) vs Fortaleza",
    liga:       "Brasileirao B",
    prediccion: "Over 2.5 goles",
    cuota:      "2.40",
    hora:       "16:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "30/05/26",
    partido:    "PSG vs Arsenal",
    liga:       "UEFA Champions League Final",
    prediccion: "Under 2.5 goles (a >=1.90)",
    cuota:      "1.90",
    hora:       "11:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  }
];

const PREDICCIONES_HISTORIAL = [
  {
    fecha:      "25/06/26",
    partido:    "Paraguay vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.73",
    prob:       "58",
    resultado:  "loss"
  },
  {
    fecha:      "25/06/26",
    partido:    "Turkey vs USA",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.62",
    prob:       "61",
    resultado:  "loss"
  },
  {
    fecha:      "25/06/26",
    partido:    "Paraguay vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.6",
    prob:       "63",
    resultado:  "push"
  },
  {
    fecha:      "25/06/26",
    partido:    "Turkey vs USA",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Visitante",
    cuota:      "1.44",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "25/06/26",
    partido:    "Ecuador vs Germany",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.53",
    prob:       "64",
    resultado:  "win"
  },
  {
    fecha:      "25/06/26",
    partido:    "Curaçao vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.76",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Czech Republic vs Mexico",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.35",
    prob:       "73",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "South Africa vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.77",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Scotland vs Brazil",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2.25",
    cuota:      "1.4",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "24/06/26",
    partido:    "Morocco vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.33",
    prob:       "76",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Bosnia & Herzegovina vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.42",
    prob:       "69",
    resultado:  "win"
  },
  {
    fecha:      "24/06/26",
    partido:    "Bosnia & Herzegovina vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "2.08",
    prob:       "49",
    resultado:  "loss"
  },
  {
    fecha:      "24/06/26",
    partido:    "Switzerland vs Canada",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.91",
    prob:       "55",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "Colombia vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1.5",
    cuota:      "1.54",
    prob:       "64",
    resultado:  "win"
  },
  {
    fecha:      "23/06/26",
    partido:    "Panama vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.98",
    prob:       "52",
    resultado:  "loss"
  },
  {
    fecha:      "23/06/26",
    partido:    "England vs Ghana",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.61",
    prob:       "62",
    resultado:  "loss"
  },
  {
    fecha:      "23/06/26",
    partido:    "Portugal vs Uzbekistan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.7",
    prob:       "60",
    resultado:  "loss"
  },
  {
    fecha:      "23/06/26",
    partido:    "Cincinnati Reds vs Milwaukee Brewers",
    liga:       "MLB",
    prediccion: "Gana Cincinnati Reds",
    cuota:      "2.02",
    prob:       "50",
    resultado:  "loss"
  },
  {
    fecha:      "22/06/26",
    partido:    "Norway vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.41",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "22/06/26",
    partido:    "Jordan vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "France vs Iraq",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.35",
    prob:       "73",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "Argentina vs Austria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "New Zealand vs Egypt",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.35",
    prob:       "73",
    resultado:  "win"
  },
  {
    fecha:      "22/06/26",
    partido:    "Shamrock Rovers vs Derry City",
    liga:       "League of Ireland",
    prediccion: "Ambos No Marcan",
    cuota:      "1.75",
    prob:       "71",
    resultado:  "loss"
  },
  {
    fecha:      "21/06/26",
    partido:    "Uruguay vs Cape Verde",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.4",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "Belgium vs Iran",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.44",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "21/06/26",
    partido:    "Spain vs Saudi Arabia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Under 10.5",
    cuota:      "1.76",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Tunisia vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.37",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Ecuador vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    prob:       "62",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Germany vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2.25",
    cuota:      "1.32",
    prob:       "75",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Netherlands vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    prob:       "62",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Turkey vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.94",
    prob:       "52",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Brazil vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.36",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Hamilton Tiger-Cats vs BC Lions",
    liga:       "CFL",
    prediccion: "Gana Hamilton Tiger-Cats",
    cuota:      "1.87",
    prob:       "56",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Scotland vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.81",
    prob:       "58",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Connecticut Sun vs Toronto Tempo",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "1.92",
    prob:       "53",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "USA vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.3",
    prob:       "76",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Mexico vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.48",
    prob:       "67",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Canada vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.33",
    prob:       "74",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Universidad de Chile vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.79",
    prob:       "79",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Sport Recife vs Atletico Goianiense",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.91",
    prob:       "76",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.6",
    prob:       "62",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.4",
    prob:       "70",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Czech Republic vs South Africa",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.41",
    prob:       "71",
    resultado:  "push"
  },
  {
    fecha:      "18/06/26",
    partido:    "Indiana Fever vs Atlanta Dream",
    liga:       "WNBA",
    prediccion: "Gana Indiana Fever",
    cuota:      "2.0",
    prob:       "51",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Ghana vs Panama",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +0.75",
    cuota:      "1.46",
    prob:       "67",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Uzbekistan vs Colombia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    prob:       "72",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "England vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1.5",
    cuota:      "1.41",
    prob:       "69",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Portugal vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.31",
    prob:       "75",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Connecticut Sun vs Washington Mystics",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "2.25",
    prob:       "46",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 2.5",
    cuota:      "2.2",
    prob:       "49",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1",
    cuota:      "2.18",
    prob:       "49",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Austria vs Jordan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.4",
    prob:       "71",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.61",
    prob:       "63",
    resultado:  "win"
  },
  {
    fecha:      "15/06/26",
    partido:    "Iran vs New Zealand",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.52",
    resultado:  "win"
  },
  {
    fecha:      "15/06/26",
    partido:    "Belgium vs Egypt",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Over 3.5",
    cuota:      "2.08",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Sweden vs Tunisia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 4.5",
    cuota:      "1.47",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Netherlands vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1",
    cuota:      "1.41",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Ivory Coast vs Ecuador",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.44",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Juventude vs Ponte Preta",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.65",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Germany vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "1.44",
    resultado:  "loss"
  },
  {
    fecha:      "14/06/26",
    partido:    "Union La Calera vs Universidad de Chile",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.87",
    resultado:  "loss"
  },
  {
    fecha:      "14/06/26",
    partido:    "Sweden vs Tunisia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 4.5",
    cuota:      "1.47",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Ivory Coast vs Ecuador",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.44",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Netherlands vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1",
    cuota:      "1.41",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Coquimbo Unido vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.83",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Louisville Kings vs DC Defenders",
    liga:       "UFL",
    prediccion: "Gana Louisville Kings",
    cuota:      "2.0",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Brazil vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local -0.25",
    cuota:      "1.48",
    resultado:  "loss"
  },
  {
    fecha:      "13/06/26",
    partido:    "Qatar vs Switzerland",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2.5",
    cuota:      "1.48",
    resultado:  "win"
  },
  {
    fecha:      "12/06/26",
    partido:    "USA vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 3.5",
    cuota:      "2.12",
    resultado:  "loss"
  },
  {
    fecha:      "12/06/26",
    partido:    "Canada vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.43",
    resultado:  "win"
  },
  {
    fecha:      "10/06/26",
    partido:    "Sport Recife vs Athletic Club (MG)",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.75",
    resultado:  "win"
  },
  {
    fecha:      "08/06/26",
    partido:    "Vila Nova vs Botafogo",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.49",
    resultado:  "win"
  },
  {
    fecha:      "07/06/26",
    partido:    "Bergischer HC vs Frisch Auf Göppingen",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana Frisch Auf Göppingen",
    cuota:      "1.92",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "THW Kiel vs TBV Lemgo",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana THW Kiel",
    cuota:      "1.71",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "ThSV Eisenach vs HSV Hamburg",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana ThSV Eisenach",
    cuota:      "1.67",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Nice vs Saint Etienne",
    liga:       "Ligue 1",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.62",
    resultado:  "loss"
  },
  {
    fecha:      "31/05/26",
    partido:    "Gent vs Genk",
    liga:       "Belgian First Div",
    prediccion: "Under 2.5 Goles",
    cuota:      "2.05",
    resultado:  "win"
  },
  {
    fecha:      "31/05/26",
    partido:    "Palmeiras vs Chapecoense",
    liga:       "Brasileirao Serie A",
    prediccion: "Gana Palmeiras",
    cuota:      "1.37",
    resultado:  "win"
  },
  {
    fecha:      "02/06/26",
    partido:    "Carolina Hurricanes vs Vegas Golden Knights",
    liga:       "NHL",
    prediccion: "Gana Vegas Golden Knights",
    cuota:      "3.0",
    resultado:  "loss"
  },
  {
    fecha:      "04/06/26",
    partido:    "HSV Hamburg vs HSG Wetzlar",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana HSV Hamburg",
    cuota:      "1.77",
    resultado:  "win"
  },
  {
    fecha:      "06/06/26",
    partido:    "Tokyo Verdy vs Gamba Osaka",
    liga:       "J-League",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.5",
    resultado:  "loss"
  },
  {
    fecha:      "05/06/26",
    partido:    "Texas Rangers vs Cleveland Guardians",
    liga:       "MLB",
    prediccion: "Gana Texas Rangers",
    cuota:      "2.24",
    resultado:  "win"
  },
  {
    fecha:      "06/06/26",
    partido:    "FC Tokyo vs Cerezo Osaka",
    liga:       "J-League",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.7",
    resultado:  "win"
  },
  {
    fecha:      "29/05/26",
    partido:    "Carolina Hurricanes vs Montréal Canadiens",
    liga:       "NHL",
    prediccion: "Gana Carolina Hurricanes",
    cuota:      "1.70",
    resultado:  "loss"
  },
  {
    fecha:      "30/05/26",
    partido:    "PSG vs Arsenal",
    liga:       "UEFA Champions League Final",
    prediccion: "Under 2.5 goles (a >=1.90)",
    cuota:      "1.90",
    resultado:  "win"
  },
  {
    fecha:      "30/05/26",
    partido:    "Athletic Club (MG) vs Fortaleza",
    liga:       "Brasileirao B",
    prediccion: "Over 2.5 goles",
    cuota:      "2.40",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Boca Juniors vs U. Católica (Chile)",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "2.01",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Cerro Porteño vs Sporting Cristal",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.89",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "América de Cali vs Macará",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "1.82",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Bolívar vs Independiente Rivadavia",
    liga:       "Copa Libertadores",
    prediccion: "Gana Bolívar",
    cuota:      "2.32",
    resultado:  "loss"
  },
  {
    fecha:      "28/05/26",
    partido:    "Corinthians vs Platense",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.96",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Peñarol vs Independiente Santa Fe",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.79",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "RB Bragantino vs Carabobo FC",
    liga:       "Copa Sudamericana",
    prediccion: "Over 2.5 goles",
    cuota:      "1.89",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Atlético Mineiro vs Academia Puerto Cabello",
    liga:       "Copa Sudamericana",
    prediccion: "Over 2.5 goles",
    cuota:      "1.86",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Libertad Asuncion vs UCV FC",
    liga:       "Copa Sudamericana",
    prediccion: "Gana Libertad Asuncion",
    cuota:      "1.43",
    resultado:  "loss"
  },
  {
    fecha:      "28/05/26",
    partido:    "Corinthians vs Platense",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.96",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Peñarol vs Independiente Santa Fe",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.79",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Bolívar vs Independiente Rivadavia",
    liga:       "Copa Libertadores",
    prediccion: "Gana Bolívar",
    cuota:      "2.32",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Nishesh Basavareddy vs Alex Michelsen",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Alex Michelsen",
    cuota:      "1.56",
    resultado:  "pendiente"
  },
  {
    fecha:      "27/05/26",
    partido:    "Francesca Jones vs Marie Bouzkova",
    liga:       "WTA Roland Garros",
    prediccion: "Gana Marie Bouzkova",
    cuota:      "1.29",
    resultado:  "pendiente"
  },
  {
    fecha:      "27/05/26",
    partido:    "Cienciano vs CA Juventud",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "1.81",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "Caracas FC vs Botafogo",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "1.75",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Montréal Canadiens vs Carolina Hurricanes",
    liga:       "NHL",
    prediccion: "Gana Montréal Canadiens",
    cuota:      "3.05",
    resultado:  "loss"
  },
  {
    fecha:      "26/05/26",
    partido:    "Vegas Golden Knights vs Colorado Avalanche",
    liga:       "NHL",
    prediccion: "Gana Vegas Golden Knights",
    cuota:      "2.7",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "Olimpia Asunción vs Audax Italiano",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "2.01",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "Jelena Ostapenko vs Magda Linette",
    liga:       "WTA Roland Garros",
    prediccion: "Gana Jelena Ostapenko",
    cuota:      "1.3",
    resultado:  "win"
  },
  {
    fecha:      "26/05/26",
    partido:    "Milwaukee Brewers vs St. Louis Cardinals",
    liga:       "MLB",
    prediccion: "Gana Milwaukee Brewers",
    cuota:      "1.56",
    resultado:  "win"
  },
  {
    fecha:      "26/05/26",
    partido:    "Vit Kopriva vs Corentin Moutet",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Corentin Moutet",
    cuota:      "1.55",
    resultado:  "loss"
  },
  {
    fecha:      "26/05/26",
    partido:    "Marin Cilic vs Moise Kouame",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Marin Cilic",
    cuota:      "1.29",
    resultado:  "loss"
  },
  {
    fecha:      "26/05/26",
    partido:    "Oklahoma City Thunder vs San Antonio Spurs",
    liga:       "NBA",
    prediccion: "Gana Oklahoma City Thunder",
    cuota:      "1.62",
    resultado:  "win"
  },
  {
    fecha:      "25/05/26",
    partido:    "Mariano Navone vs Jenson Brooksby",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Mariano Navone",
    cuota:      "1.29",
    resultado:  "win"
  },
  {
    fecha:      "25/05/26",
    partido:    "Cleveland Cavaliers vs New York Knicks",
    liga:       "NBA Playoffs",
    prediccion: "Gana New York Knicks",
    cuota:      "1.81",
    resultado:  "win"
  }
];
const ANALISIS_DIA = [

];
