// SharpIQ — ARCHIVO DE DATOS
// Actualizado: 2026-05-29
// NO editar manualmente

const PROXIMOS_EVENTOS = [
  {
    fecha:      "21/06/26",
    partido:    "New Zealand vs Egypt",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.33",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "pendiente"
  },
  {
    fecha:      "21/06/26",
    partido:    "Uruguay vs Cape Verde",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.46",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "68",
    resultado:  "pendiente"
  },
  {
    fecha:      "21/06/26",
    partido:    "New Zealand vs Egypt",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.38",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "pendiente"
  },
  {
    fecha:      "21/06/26",
    partido:    "Belgium vs Iran",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.44",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "pendiente"
  },
  {
    fecha:      "21/06/26",
    partido:    "Belgium vs Iran",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.44",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "pendiente"
  },
  {
    fecha:      "21/06/26",
    partido:    "Spain vs Saudi Arabia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Under 10.5",
    cuota:      "1.76",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "58",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "21/06/26",
    partido:    "Spain vs Saudi Arabia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.38",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Tunisia vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.37",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Tunisia vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Visitante",
    cuota:      "1.51",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Ecuador vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Germany vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2.25",
    cuota:      "1.32",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "75",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Germany vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2",
    cuota:      "1.35",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Netherlands vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Netherlands vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.34",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Ecuador vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "1.44",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "68",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Orix Buffaloes vs Saitama Seibu Lions",
    liga:       "NPB",
    prediccion: "Gana Orix Buffaloes",
    cuota:      "2.19",
    hora:       "00:00 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.0",
    prob:       "47",
    resultado:  "pendiente"
  },
  {
    fecha:      "19/06/26",
    partido:    "Turkey vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.94",
    hora:       "22:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "52",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Turkey vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.38",
    hora:       "22:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Brazil vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.36",
    hora:       "19:30 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Connecticut Sun vs Toronto Tempo",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "1.92",
    hora:       "18:40 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.1",
    prob:       "53",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Brazil vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 4.5 Goles",
    cuota:      "1.51",
    hora:       "19:30 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Scotland vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.81",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "58",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Scotland vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.47",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "USA vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.3",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "76",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "NC Dinos vs SSG Landers",
    liga:       "KBO",
    prediccion: "Gana NC Dinos",
    cuota:      "2.1",
    hora:       "04:30 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.3",
    prob:       "49",
    resultado:  "pendiente"
  },
  {
    fecha:      "19/06/26",
    partido:    "USA vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.39",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Hamilton Tiger-Cats vs BC Lions",
    liga:       "CFL",
    prediccion: "Gana Hamilton Tiger-Cats",
    cuota:      "1.87",
    hora:       "18:30 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "2.2",
    prob:       "56",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Sport Recife vs Atletico Goianiense",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.91",
    hora:       "19:02 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "76",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Mexico vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.48",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Universidad de Chile vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.79",
    hora:       "19:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "79",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Mexico vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.42",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Canada vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.33",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "74",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.4",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Indiana Fever vs Atlanta Dream",
    liga:       "WNBA",
    prediccion: "Gana Indiana Fever",
    cuota:      "2.0",
    hora:       "18:40 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.4",
    prob:       "51",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Czech Republic vs South Africa",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.41",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "push",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.6",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "62",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Canada vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.49",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Czech Republic vs South Africa",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.4",
    hora:       "11:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "push",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Uzbekistan vs Colombia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "loss",
    resultado:  "push"
  },
  {
    fecha:      "17/06/26",
    partido:    "Ghana vs Panama",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +0.75",
    cuota:      "1.46",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Ghana vs Panama",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.49",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "66",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "England vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1.5",
    cuota:      "1.41",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "69",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Uzbekistan vs Colombia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2",
    cuota:      "1.4",
    hora:       "21:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "70",
    resultado:  "push",
    resultado:  "push"
  },
  {
    fecha:      "17/06/26",
    partido:    "England vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.38",
    hora:       "15:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Portugal vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.31",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "75",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Portugal vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.45",
    hora:       "12:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "68",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Connecticut Sun vs Washington Mystics",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "2.25",
    hora:       "18:00 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.0",
    prob:       "46",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Austria vs Jordan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.4",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "71",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1",
    cuota:      "2.18",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "49",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2",
    cuota:      "1.32",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "77",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Austria vs Jordan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.43",
    hora:       "23:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "1.0",
    prob:       "69",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Over 3.5",
    cuota:      "1.74",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "61",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.48",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Under 8.5",
    cuota:      "1.83",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "58",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.36",
    hora:       "20:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "72",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 2.5",
    cuota:      "2.2",
    hora:       "17:05 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "49",
    resultado:  "win",
    resultado:  "win",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 3.5",
    cuota:      "1.51",
    hora:       "17:05 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "67",
    resultado:  "win",
    resultado:  "win",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.7",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "principal",
    stake_pct:  "1.4",
    prob:       "60",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.57",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "63",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.61",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "63",
    resultado:  "win",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Over 2.5",
    cuota:      "1.4",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "70",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 7.5",
    cuota:      "1.42",
    hora:       "17:00 COT",
    status:     "vip",
    tier:       "seguro",
    stake_pct:  "3",
    prob:       "69",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "2.0",
    hora:       "14:00 COT",
    status:     "vip",
    tier:       "alto_valor",
    stake_pct:  "2",
    prob:       "51",
    resultado:  "win",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Sweden vs Tunisia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 4.5",
    cuota:      "1.47",
    hora:       "21:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Qatar vs Switzerland",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2.5",
    cuota:      "1.48",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Brazil vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local -0.25",
    cuota:      "1.48",
    hora:       "17:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Germany vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "1.44",
    hora:       "12:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "14/06/26",
    partido:    "Juventude vs Ponte Preta",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.65",
    hora:       "09:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "12/06/26",
    partido:    "USA vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 3.5",
    cuota:      "2.12",
    hora:       "20:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "13/06/26",
    partido:    "Louisville Kings vs DC Defenders",
    liga:       "UFL",
    prediccion: "Gana Louisville Kings",
    cuota:      "2.0",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Coquimbo Unido vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.83",
    hora:       "11:30 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "12/06/26",
    partido:    "Canada vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.43",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "10/06/26",
    partido:    "Sport Recife vs Athletic Club (MG)",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.75",
    hora:       "19:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "08/06/26",
    partido:    "Vila Nova vs Botafogo",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.49",
    hora:       "18:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "07/06/26",
    partido:    "ThSV Eisenach vs HSV Hamburg",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana ThSV Eisenach",
    cuota:      "1.67",
    hora:       "08:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "THW Kiel vs TBV Lemgo",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana THW Kiel",
    cuota:      "1.71",
    hora:       "08:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "Bergischer HC vs Frisch Auf Göppingen",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana Frisch Auf Göppingen",
    cuota:      "1.92",
    hora:       "08:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "06/06/26",
    partido:    "FC Tokyo vs Cerezo Osaka",
    liga:       "J-League",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.7",
    hora:       "00:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "05/06/26",
    partido:    "Texas Rangers vs Cleveland Guardians",
    liga:       "MLB",
    prediccion: "Gana Texas Rangers",
    cuota:      "2.24",
    hora:       "19:16 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "06/06/26",
    partido:    "Tokyo Verdy vs Gamba Osaka",
    liga:       "J-League",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.5",
    hora:       "02:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "04/06/26",
    partido:    "HSV Hamburg vs HSG Wetzlar",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana HSV Hamburg",
    cuota:      "1.77",
    hora:       "12:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "02/06/26",
    partido:    "Carolina Hurricanes vs Vegas Golden Knights",
    liga:       "NHL",
    prediccion: "Gana Vegas Golden Knights",
    cuota:      "3.0",
    hora:       "19:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "31/05/26",
    partido:    "Palmeiras vs Chapecoense",
    liga:       "Brasileirao Serie A",
    prediccion: "Gana Palmeiras",
    cuota:      "1.37",
    hora:       "14:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "31/05/26",
    partido:    "Gent vs Genk",
    liga:       "Belgian First Div",
    prediccion: "Under 2.5 Goles",
    cuota:      "2.05",
    hora:       "11:30 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "29/05/26",
    partido:    "Nice vs Saint Etienne",
    liga:       "Ligue 1",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.62",
    hora:       "13:45 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Carolina Hurricanes vs Montréal Canadiens",
    liga:       "NHL",
    prediccion: "Gana Carolina Hurricanes",
    cuota:      "1.70",
    hora:       "19:15 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Boca Juniors vs U. Católica (Chile)",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "2.01",
    hora:       "19:30 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  },
  {
    fecha:      "30/05/26",
    partido:    "Athletic Club (MG) vs Fortaleza",
    liga:       "Brasileirao B",
    prediccion: "Over 2.5 goles",
    cuota:      "2.40",
    hora:       "16:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "loss"
  },
  {
    fecha:      "30/05/26",
    partido:    "PSG vs Arsenal",
    liga:       "UEFA Champions League Final",
    prediccion: "Under 2.5 goles (a >=1.90)",
    cuota:      "1.90",
    hora:       "11:00 COT",
    emoji:      "",
    status:     "vip",
    resultado:  "win"
  }
];

const PREDICCIONES_HISTORIAL = [
  {
    fecha:      "21/06/26",
    partido:    "Spain vs Saudi Arabia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Under 10.5",
    cuota:      "1.76",
    prob:       "58",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Tunisia vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.37",
    prob:       "72",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Ecuador vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    prob:       "62",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Germany vs Ivory Coast",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +2.25",
    cuota:      "1.32",
    prob:       "75",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "20/06/26",
    partido:    "Netherlands vs Sweden",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.58",
    prob:       "62",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Turkey vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos Marcan",
    cuota:      "1.94",
    prob:       "52",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Brazil vs Haiti",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.36",
    prob:       "72",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Hamilton Tiger-Cats vs BC Lions",
    liga:       "CFL",
    prediccion: "Gana Hamilton Tiger-Cats",
    cuota:      "1.87",
    prob:       "56",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "Scotland vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.81",
    prob:       "58",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "19/06/26",
    partido:    "Connecticut Sun vs Toronto Tempo",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "1.92",
    prob:       "53",
    resultado:  "win"
  },
  {
    fecha:      "19/06/26",
    partido:    "USA vs Australia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.3",
    prob:       "76",
    resultado:  "win",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Mexico vs South Korea",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.48",
    prob:       "67",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Canada vs Qatar",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.33",
    prob:       "74",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Universidad de Chile vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.79",
    prob:       "79",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Sport Recife vs Atletico Goianiense",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.91",
    prob:       "76",
    resultado:  "loss"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.6",
    prob:       "62",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Switzerland vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.4",
    prob:       "70",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Czech Republic vs South Africa",
    liga:       "FIFA Mundial 2026",
    prediccion: "Draw No Bet Local",
    cuota:      "1.41",
    prob:       "71",
    resultado:  "push",
    resultado:  "win"
  },
  {
    fecha:      "18/06/26",
    partido:    "Indiana Fever vs Atlanta Dream",
    liga:       "WNBA",
    prediccion: "Gana Indiana Fever",
    cuota:      "2.0",
    prob:       "51",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Ghana vs Panama",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +0.75",
    cuota:      "1.46",
    prob:       "67",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "17/06/26",
    partido:    "Uzbekistan vs Colombia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 3.5 Goles",
    cuota:      "1.38",
    prob:       "72",
    resultado:  "loss",
    resultado:  "push"
  },
  {
    fecha:      "17/06/26",
    partido:    "England vs Croatia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1.5",
    cuota:      "1.41",
    prob:       "69",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Portugal vs DR Congo",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.31",
    prob:       "75",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "17/06/26",
    partido:    "Connecticut Sun vs Washington Mystics",
    liga:       "WNBA",
    prediccion: "Gana Connecticut Sun",
    cuota:      "2.25",
    prob:       "46",
    resultado:  "win"
  },
  {
    fecha:      "16/06/26",
    partido:    "Iraq vs Norway",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 2.5",
    cuota:      "2.2",
    prob:       "49",
    resultado:  "win",
    resultado:  "win",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Argentina vs Algeria",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Visitante +1",
    cuota:      "2.18",
    prob:       "49",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "loss",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "Austria vs Jordan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Victoria Local",
    cuota:      "1.4",
    prob:       "71",
    resultado:  "win",
    resultado:  "loss"
  },
  {
    fecha:      "16/06/26",
    partido:    "France vs Senegal",
    liga:       "FIFA Mundial 2026",
    prediccion: "Corners Over 8.5",
    cuota:      "1.61",
    prob:       "63",
    resultado:  "win",
    resultado:  "loss",
    resultado:  "win"
  },
  {
    fecha:      "15/06/26",
    partido:    "Iran vs New Zealand",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.52",
    resultado:  "win"
  },
  {
    fecha:      "15/06/26",
    partido:    "Belgium vs Egypt",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Over 3.5",
    cuota:      "2.08",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Sweden vs Tunisia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 4.5",
    cuota:      "1.47",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Netherlands vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1",
    cuota:      "1.41",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Ivory Coast vs Ecuador",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.44",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Juventude vs Ponte Preta",
    liga:       "Brasileirao B",
    prediccion: "Ambos No Marcan",
    cuota:      "1.65",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Germany vs Curaçao",
    liga:       "FIFA Mundial 2026",
    prediccion: "Ambos No Marcan",
    cuota:      "1.44",
    resultado:  "loss"
  },
  {
    fecha:      "14/06/26",
    partido:    "Union La Calera vs Universidad de Chile",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.87",
    resultado:  "loss"
  },
  {
    fecha:      "14/06/26",
    partido:    "Sweden vs Tunisia",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 4.5",
    cuota:      "1.47",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Ivory Coast vs Ecuador",
    liga:       "FIFA Mundial 2026",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.44",
    resultado:  "win"
  },
  {
    fecha:      "14/06/26",
    partido:    "Netherlands vs Japan",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Asiático Visitante +1",
    cuota:      "1.41",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Coquimbo Unido vs O'Higgins",
    liga:       "Campeonato Chileno",
    prediccion: "Ambos No Marcan",
    cuota:      "1.83",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Louisville Kings vs DC Defenders",
    liga:       "UFL",
    prediccion: "Gana Louisville Kings",
    cuota:      "2.0",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Brazil vs Morocco",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local -0.25",
    cuota:      "1.48",
    resultado:  "win"
  },
  {
    fecha:      "13/06/26",
    partido:    "Qatar vs Switzerland",
    liga:       "FIFA Mundial 2026",
    prediccion: "Hándicap Local +2.5",
    cuota:      "1.48",
    resultado:  "win"
  },
  {
    fecha:      "12/06/26",
    partido:    "USA vs Paraguay",
    liga:       "FIFA Mundial 2026",
    prediccion: "Tarjetas Under 3.5",
    cuota:      "2.12",
    resultado:  "loss"
  },
  {
    fecha:      "12/06/26",
    partido:    "Canada vs Bosnia & Herzegovina",
    liga:       "FIFA Mundial 2026",
    prediccion: "Over 1.5 Goles",
    cuota:      "1.43",
    resultado:  "win"
  },
  {
    fecha:      "10/06/26",
    partido:    "Sport Recife vs Athletic Club (MG)",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.75",
    resultado:  "win"
  },
  {
    fecha:      "08/06/26",
    partido:    "Vila Nova vs Botafogo",
    liga:       "Brasileirao B",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.49",
    resultado:  "win"
  },
  {
    fecha:      "07/06/26",
    partido:    "Bergischer HC vs Frisch Auf Göppingen",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana Frisch Auf Göppingen",
    cuota:      "1.92",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "THW Kiel vs TBV Lemgo",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana THW Kiel",
    cuota:      "1.71",
    resultado:  "loss"
  },
  {
    fecha:      "07/06/26",
    partido:    "ThSV Eisenach vs HSV Hamburg",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana ThSV Eisenach",
    cuota:      "1.67",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Nice vs Saint Etienne",
    liga:       "Ligue 1",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.62",
    resultado:  "loss"
  },
  {
    fecha:      "31/05/26",
    partido:    "Gent vs Genk",
    liga:       "Belgian First Div",
    prediccion: "Under 2.5 Goles",
    cuota:      "2.05",
    resultado:  "win"
  },
  {
    fecha:      "31/05/26",
    partido:    "Palmeiras vs Chapecoense",
    liga:       "Brasileirao Serie A",
    prediccion: "Gana Palmeiras",
    cuota:      "1.37",
    resultado:  "win"
  },
  {
    fecha:      "02/06/26",
    partido:    "Carolina Hurricanes vs Vegas Golden Knights",
    liga:       "NHL",
    prediccion: "Gana Vegas Golden Knights",
    cuota:      "3.0",
    resultado:  "loss"
  },
  {
    fecha:      "04/06/26",
    partido:    "HSV Hamburg vs HSG Wetzlar",
    liga:       "Balonmano Bundesliga",
    prediccion: "Gana HSV Hamburg",
    cuota:      "1.77",
    resultado:  "win"
  },
  {
    fecha:      "06/06/26",
    partido:    "Tokyo Verdy vs Gamba Osaka",
    liga:       "J-League",
    prediccion: "Under 2.5 Goles",
    cuota:      "1.5",
    resultado:  "loss"
  },
  {
    fecha:      "05/06/26",
    partido:    "Texas Rangers vs Cleveland Guardians",
    liga:       "MLB",
    prediccion: "Gana Texas Rangers",
    cuota:      "2.24",
    resultado:  "win"
  },
  {
    fecha:      "06/06/26",
    partido:    "FC Tokyo vs Cerezo Osaka",
    liga:       "J-League",
    prediccion: "Over 2.5 Goles",
    cuota:      "1.7",
    resultado:  "win"
  },
  {
    fecha:      "29/05/26",
    partido:    "Carolina Hurricanes vs Montréal Canadiens",
    liga:       "NHL",
    prediccion: "Gana Carolina Hurricanes",
    cuota:      "1.70",
    resultado:  "loss"
  },
  {
    fecha:      "30/05/26",
    partido:    "PSG vs Arsenal",
    liga:       "UEFA Champions League Final",
    prediccion: "Under 2.5 goles (a >=1.90)",
    cuota:      "1.90",
    resultado:  "win"
  },
  {
    fecha:      "30/05/26",
    partido:    "Athletic Club (MG) vs Fortaleza",
    liga:       "Brasileirao B",
    prediccion: "Over 2.5 goles",
    cuota:      "2.40",
    resultado:  "loss"
  },
  {
    fecha:      "29/05/26",
    partido:    "Boca Juniors vs U. Católica (Chile)",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "2.01",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Cerro Porteño vs Sporting Cristal",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.89",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "América de Cali vs Macará",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "1.82",
    resultado:  "loss"
  },
  {
    fecha:      "28/05/26",
    partido:    "Bolívar vs Independiente Rivadavia",
    liga:       "Copa Libertadores",
    prediccion: "Gana Bolívar",
    cuota:      "2.32",
    resultado:  "loss"
  },
  {
    fecha:      "28/05/26",
    partido:    "Corinthians vs Platense",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.96",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Peñarol vs Independiente Santa Fe",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.79",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "RB Bragantino vs Carabobo FC",
    liga:       "Copa Sudamericana",
    prediccion: "Over 2.5 goles",
    cuota:      "1.89",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Atlético Mineiro vs Academia Puerto Cabello",
    liga:       "Copa Sudamericana",
    prediccion: "Over 2.5 goles",
    cuota:      "1.86",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Libertad Asuncion vs UCV FC",
    liga:       "Copa Sudamericana",
    prediccion: "Gana Libertad Asuncion",
    cuota:      "1.43",
    resultado:  "loss"
  },
  {
    fecha:      "28/05/26",
    partido:    "Corinthians vs Platense",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.96",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Peñarol vs Independiente Santa Fe",
    liga:       "Copa Libertadores",
    prediccion: "Under 2.5 goles",
    cuota:      "1.79",
    resultado:  "win"
  },
  {
    fecha:      "28/05/26",
    partido:    "Bolívar vs Independiente Rivadavia",
    liga:       "Copa Libertadores",
    prediccion: "Gana Bolívar",
    cuota:      "2.32",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Nishesh Basavareddy vs Alex Michelsen",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Alex Michelsen",
    cuota:      "1.56",
    resultado:  "pendiente"
  },
  {
    fecha:      "27/05/26",
    partido:    "Francesca Jones vs Marie Bouzkova",
    liga:       "WTA Roland Garros",
    prediccion: "Gana Marie Bouzkova",
    cuota:      "1.29",
    resultado:  "pendiente"
  },
  {
    fecha:      "27/05/26",
    partido:    "Cienciano vs CA Juventud",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "1.81",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "Caracas FC vs Botafogo",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "1.75",
    resultado:  "loss"
  },
  {
    fecha:      "27/05/26",
    partido:    "Montréal Canadiens vs Carolina Hurricanes",
    liga:       "NHL",
    prediccion: "Gana Montréal Canadiens",
    cuota:      "3.05",
    resultado:  "loss"
  },
  {
    fecha:      "26/05/26",
    partido:    "Vegas Golden Knights vs Colorado Avalanche",
    liga:       "NHL",
    prediccion: "Gana Vegas Golden Knights",
    cuota:      "2.7",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "Olimpia Asunción vs Audax Italiano",
    liga:       "Copa Sudamericana",
    prediccion: "Under 2.5 goles",
    cuota:      "2.01",
    resultado:  "win"
  },
  {
    fecha:      "27/05/26",
    partido:    "Jelena Ostapenko vs Magda Linette",
    liga:       "WTA Roland Garros",
    prediccion: "Gana Jelena Ostapenko",
    cuota:      "1.3",
    resultado:  "win"
  },
  {
    fecha:      "26/05/26",
    partido:    "Milwaukee Brewers vs St. Louis Cardinals",
    liga:       "MLB",
    prediccion: "Gana Milwaukee Brewers",
    cuota:      "1.56",
    resultado:  "win"
  },
  {
    fecha:      "26/05/26",
    partido:    "Vit Kopriva vs Corentin Moutet",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Corentin Moutet",
    cuota:      "1.55",
    resultado:  "loss"
  },
  {
    fecha:      "26/05/26",
    partido:    "Marin Cilic vs Moise Kouame",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Marin Cilic",
    cuota:      "1.29",
    resultado:  "loss"
  },
  {
    fecha:      "26/05/26",
    partido:    "Oklahoma City Thunder vs San Antonio Spurs",
    liga:       "NBA",
    prediccion: "Gana Oklahoma City Thunder",
    cuota:      "1.62",
    resultado:  "win"
  },
  {
    fecha:      "25/05/26",
    partido:    "Mariano Navone vs Jenson Brooksby",
    liga:       "ATP Roland Garros",
    prediccion: "Gana Mariano Navone",
    cuota:      "1.29",
    resultado:  "win"
  },
  {
    fecha:      "25/05/26",
    partido:    "Cleveland Cavaliers vs New York Knicks",
    liga:       "NBA Playoffs",
    prediccion: "Gana New York Knicks",
    cuota:      "1.81",
    resultado:  "win"
  }
];
const ANALISIS_DIA = [
  { partido: "Países Bajos vs Suecia", liga: "FIFA Mundial 2026", titulo: "Países Bajos vs Suecia promete goles", cuerpo: "Todo apunta a un partido abierto: el modelo da 59.0% de Over 2.5 goles. Ojo con Suecia, que llega en gran forma y promedia 3.391 goles.", cuerpo_largo: "Todo apunta a un partido abierto: el modelo da 59.0% de Over 2.5 goles. Ojo con Suecia, que llega en gran forma y promedia 3.391 goles. En el 1X2, el modelo da 55.5% a Países Bajos, 23.9% al empate y 20.7% a Suecia. De cara al gol, hay un 59.0% de chance de superar los 2.5 tantos.", hora: "17:00", slug: "paises-bajos-vs-suecia", fL: "0.463", aL: "1.605", dL: "1.48", fV: "0.814", aV: "3.391", dV: "1.554", vl: "55.5", ve: "23.9", vv: "20.7", o25: "59.0", u25: "41.0" },
  { partido: "Alemania vs Ivory Coast", liga: "FIFA Mundial 2026", titulo: "Alemania, favorito para imponerse a Ivory Coast", cuerpo: "Los numeros respaldan a Alemania, con un 64.8% de probabilidad de ganar. En ataque, Alemania viene fino: 4.878 goles de media.", cuerpo_largo: "Los numeros respaldan a Alemania, con un 64.8% de probabilidad de ganar. En ataque, Alemania viene fino: 4.878 goles de media. La probabilidad de resultado queda asi: 64.8% local, 20.4% empate, 14.8% visitante. En goles, el modelo proyecta un 59.9% de Over 2.5.", hora: "20:00", slug: "alemania-vs-ivory-coast", fL: "1.0", aL: "4.878", dL: "1.062", fV: "1.0", aV: "1.603", dV: "0.139", vl: "64.8", ve: "20.4", vv: "14.8", o25: "59.9", u25: "40.1" },
  { partido: "Ecuador vs Curaçao", liga: "FIFA Mundial 2026", titulo: "Ecuador buscara dominar a Curaçao", cuerpo: "Ecuador llega como el equipo a batir, con 85.0% segun el modelo. Ninguno de los dos llega especialmente fino en ataque.", cuerpo_largo: "Ecuador llega como el equipo a batir, con 85.0% segun el modelo. Ninguno de los dos llega especialmente fino en ataque. En el 1X2, el modelo da 85.0% a Ecuador, 10.9% al empate y 4.2% a Curaçao. De cara al gol, hay un 60.4% de chance de superar los 2.5 tantos.", hora: "00:00", slug: "ecuador-vs-curacao", fL: "0.375", aL: "0.985", dL: "0.837", fV: "0.123", aV: "1.18", dV: "4.438", vl: "85.0", ve: "10.9", vv: "4.2", o25: "60.4", u25: "39.6" },
  { partido: "Túnez vs Japón", liga: "FIFA Mundial 2026", titulo: "Japón parte con ventaja sobre Túnez", cuerpo: "El modelo ve a Japón como claro favorito (62.9%) en este cruce. Ambos vienen con cifras goleadoras discretas.", cuerpo_largo: "El modelo ve a Japón como claro favorito (62.9%) en este cruce. Ambos vienen con cifras goleadoras discretas. La probabilidad de resultado queda asi: 13.7% local, 23.4% empate, 62.9% visitante. En goles, el modelo proyecta un 45.6% de Over 2.5.", hora: "04:00", slug: "tunez-vs-japon", fL: "0.14", aL: "0.58", dL: "3.355", fV: "0.68", aV: "1.68", dV: "0.96", vl: "13.7", ve: "23.4", vv: "62.9", o25: "45.6", u25: "54.4" },
  { partido: "España vs Arabia Saudita", liga: "FIFA Mundial 2026", titulo: "España, favorito para imponerse a Arabia Saudita", cuerpo: "Los numeros respaldan a España, con un 87.6% de probabilidad de ganar. Ninguno de los dos llega especialmente fino en ataque.", cuerpo_largo: "Los numeros respaldan a España, con un 87.6% de probabilidad de ganar. Ninguno de los dos llega especialmente fino en ataque. En el 1X2, el modelo da 87.6% a España, 8.7% al empate y 3.6% a Arabia Saudita. De cara al gol, hay un 66.6% de chance de superar los 2.5 tantos.", hora: "16:00", slug: "espana-vs-arabia-saudita", fL: "0.509", aL: "0.929", dL: "0.302", fV: "0.353", aV: "1.114", dV: "0.916", vl: "87.6", ve: "8.7", vv: "3.6", o25: "66.6", u25: "33.4" },
  { partido: "Almería vs Málaga", liga: "Segunda División", titulo: "Almería vs Málaga, a cara o cruz", cuerpo: "Duelo de pronostico reservado, con ligero favoritismo local. Ambos vienen con cifras goleadoras discretas.", cuerpo_largo: "Duelo de pronostico reservado, con ligero favoritismo local. Ambos vienen con cifras goleadoras discretas. La probabilidad de resultado queda asi: 45.4% local, 29.0% empate, 25.6% visitante. En goles, el modelo proyecta un 41.2% de Over 2.5.", hora: "19:00", slug: "almeria-vs-malaga", fL: "0", aL: "0", dL: "0", fV: "0", aV: "0", dV: "0", vl: "45.4", ve: "29.0", vv: "25.6", o25: "41.2", u25: "52.6" },
  { partido: "Ceará vs Botafogo", liga: "Brasileirao B", titulo: "Ceará vs Botafogo, partido de pocos goles", cuerpo: "Pinta cerrado y de pocos goles: 60.5% de probabilidad de Under 2.5. Ojo con Botafogo, que viene irregular y promedia 2.071 goles.", cuerpo_largo: "Pinta cerrado y de pocos goles: 60.5% de probabilidad de Under 2.5. Ojo con Botafogo, que viene irregular y promedia 2.071 goles. En el 1X2, el modelo da 49.4% a Ceará, 29.2% al empate y 21.4% a Botafogo. De cara al gol, hay un 39.5% de chance de superar los 2.5 tantos.", hora: "22:00", slug: "ceara-vs-botafogo", fL: "0", aL: "0", dL: "0", fV: "0.6", aV: "2.071", dV: "1.104", vl: "49.4", ve: "29.2", vv: "21.4", o25: "39.5", u25: "60.5" },
  { partido: "Vila Nova vs Nautico PE", liga: "Brasileirao B", titulo: "Vila Nova vs Nautico PE apunta a ser cerrado", cuerpo: "El modelo proyecta un duelo tactico, con 56.9% de Under 2.5 goles. Ambos vienen con cifras goleadoras discretas.", cuerpo_largo: "El modelo proyecta un duelo tactico, con 56.9% de Under 2.5 goles. Ambos vienen con cifras goleadoras discretas. La probabilidad de resultado queda asi: 41.1% local, 30.5% empate, 28.4% visitante. En goles, el modelo proyecta un 28.6% de Over 2.5.", hora: "22:00", slug: "vila-nova-vs-nautico-pe", fL: "0.73", aL: "1.037", dL: "0.435", fV: "0", aV: "0", dV: "0", vl: "41.1", ve: "30.5", vv: "28.4", o25: "28.6", u25: "56.9" }
];
