// Generado por radar_valor.py — NO editar a mano.
window.RADAR_VALOR = {
  "generado": "2026-07-26T21:30:12.442614+00:00",
  "total": 7,
  "jugadas": [
    {
      "deporte": "Brazil Série A",
      "emoji": "⚽",
      "estado": "VIVO",
      "partido": "Grêmio vs Fluminense",
      "jugada": "Grêmio (0.0)",
      "casa": "1xBet",
      "cuota": 2.81,
      "cuota_justa": 2.63,
      "valor": 6.9,
      "prob": 38.0,
      "betplay_cuota": null,
      "betplay_valor": null
    },
    {
      "deporte": "Brazil Série A",
      "emoji": "⚽",
      "estado": "VIVO",
      "partido": "Flamengo vs Sao Paulo",
      "jugada": "Más de 2.5 goles",
      "casa": "1xBet",
      "cuota": 1.98,
      "cuota_justa": 1.9,
      "valor": 4.3,
      "prob": 52.7,
      "betplay_cuota": null,
      "betplay_valor": null
    },
    {
      "deporte": "Boxing",
      "emoji": "🥊",
      "estado": "PRE",
      "partido": "Otto Wallin vs Vladyslav Sirenko",
      "jugada": "Gana Vladyslav Sirenko",
      "casa": "Betway",
      "cuota": 2.88,
      "cuota_justa": 2.6,
      "valor": 10.7,
      "prob": 38.4,
      "betplay_cuota": null,
      "betplay_valor": null
    },
    {
      "deporte": "Boxing",
      "emoji": "🥊",
      "estado": "PRE",
      "partido": "Sergiy Derevyanchenko vs Jalil Hackett",
      "jugada": "Gana Sergiy Derevyanchenko",
      "casa": "Betfair",
      "cuota": 2.72,
      "cuota_justa": 2.57,
      "valor": 6.0,
      "prob": 39.0,
      "betplay_cuota": null,
      "betplay_valor": null
    },
    {
      "deporte": "Boxing",
      "emoji": "🥊",
      "estado": "PRE",
      "partido": "Otto Wallin vs Vladyslav Sirenko",
      "jugada": "Gana Otto Wallin",
      "casa": "Betfair",
      "cuota": 1.72,
      "cuota_justa": 1.62,
      "valor": 5.9,
      "prob": 61.6,
      "betplay_cuota": null,
      "betplay_valor": null
    },
    {
      "deporte": "Boxing",
      "emoji": "🥊",
      "estado": "PRE",
      "partido": "Sergiy Derevyanchenko vs Jalil Hackett",
      "jugada": "Gana Jalil Hackett",
      "casa": "Betfair",
      "cuota": 1.7,
      "cuota_justa": 1.64,
      "valor": 3.8,
      "prob": 61.0,
      "betplay_cuota": null,
      "betplay_valor": null
    },
    {
      "deporte": "Liga MX",
      "emoji": "⚽",
      "estado": "PRE",
      "partido": "Necaxa vs Monterrey",
      "jugada": "Gana Monterrey",
      "casa": "1xBet",
      "cuota": 2.27,
      "cuota_justa": 2.2,
      "valor": 3.1,
      "prob": 45.4,
      "betplay_cuota": null,
      "betplay_valor": null
    }
  ]
};
